### ISSUE TITLE
DiabolicUI Minimap is too dark in some areas.

### ISSUE THREAD

**Issue by Sottises** [cogwerkz/DiabolicUI#101]
**Description**
The DiabolicUI Minimap is too dark in some areas, particularly Stormheim. There could be others.

**Version Number**
1.3.103-Release

**Steps to Reproduce**
Monitor the map while in Stormheim.

**Expected Behavior**
The map should be readable at a sensible brightness.

**Actual Behavior**
Map is too dark to clearly see roads at a glance.

**Only DiabolicUI Enabled**
The UI-changing Addons I have are: DiabolicUI, Goldpaw Core, Goldpaw Trader/Merchant, Adapt (Almost Default Animated Portraits), Bagnon, SexyMap, Masque, Engraved, rObjectiveTracker and Deadly Boss Mods. 

For this test, I disabled SexyMap.

**Additional Information**
The World Map is affected too. Likely an option to toggle or change this should be included.

**Error Log**
N/A

**Screenshot**
![DiaMap](https://user-images.githubusercontent.com/32430805/36014380-9388516a-0dbd-11e8-94b8-6ddb57b33993.png)

**Comment by goldpaw** [comment]
Not that dark. But in 1.3.107 I still made it slightly lighter, though. Did the same to the WorldMap. So hopefully that'll help a bit. :) 👍
