### ISSUE TITLE
No minimap buttons. (Feature req.)

### ISSUE THREAD

**Issue by Sottises** [cogwerkz/DiabolicUI#104]
**Description**
The minimap needs all the buttons present, even if a few fade when not hovered over. These could even be placed in a row in the bottom third of the minimap when hovered as long as they don't clickthrough and ping the map. Extra ones that come from addons can sit on the ring, and the calendar should appear next to the clock when hovered. This should also be remedied alongside the missing class hall button.

**Version Number**
1.3.103-Release

**Steps to Reproduce**
Hover over the minimap.

**Expected Behavior**
Buttons presented to use.

**Actual Behavior**
No buttons shown.

**Only DiabolicUI Enabled**
The UI-changing Addons I have are: DiabolicUI, Goldpaw Core, Goldpaw Trader/Merchant, Adapt (Almost Default Animated Portraits), Bagnon, SexyMap, Masque, Engraved, rObjectiveTracker and Deadly Boss Mods.

Sexymap was disabled for this test.

**Additional Information**
N/A

**Error Log**
N/A

**Screenshot**
N/A

**Comment by goldpaw** [comment]
- worldmap connected to the questlog anyway now
- mousewheel zooms in and out
- right-click opens the tracking menu
- calendar can be opened by left-clicking the clock
- 12/24 hour and game/local time can be toggled by mid/right buttons on the clock now 

Closing this issue as pretty much all that functionality is there already. And buttons from other addons can be accessed with MBB, as mentioned in the wiki. Will be adding a detailed Minimap section to the wiki as well! 👍
