### ISSUE TITLE
Target buffs and debuffs

### ISSUE THREAD

**Issue by goldpaw** [cogwerkz/DiabolicUI#11]
We need buffs and debuffs on the target frame. They must be filtered, yet possible to view everything. 

Buffs and debuffs should be separated, and probably displayed at opposite places for friendly and unfriendly targets. Though we should be able to see what's relevant on both, like ice block on enemy Mages or bubbles on Paladins. 

Long term buffs in client versions prior to Legion should be consolidated, to avoid them taking up valuable screen estate and clutter things up.

**Comment by AntonyMcLovin** [comment]
for what I've seen so far is, that some debuffs are not shown like bloodlust. Is it possible to show longer debuffs?
