### ISSUE TITLE
Options?

### ISSUE THREAD

**Issue by Cyph1n** [cogwerkz/DiabolicUI#112]
I may be blind but I cannot for the life of me find the options window. The size of some things are big and I'd like to resize or disable some things or even move them..

**Comment by Anderzenn** [comment]
There is currently no configuration window but Goldpaw is working on one with some basic highly requested features.

**Comment by Cyph1n** [comment]
Ah ok. Didn't know this was a brand new addon when I downloaded it lol. Didn't say anything in the addon description. But at least now I know 👍

**Comment by Kkthnx** [comment]
You can always read the Wiki for some info.
https://github.com/cogwerkz/DiabolicUI/wiki
