### ISSUE TITLE
Microbar / menu issue

### ISSUE THREAD

**Issue by christhewarlock** [cogwerkz/DiabolicUI#116]
**Description**
so i tried ur addon and i feel in love with but when i was going to press the menu button or that thing that opens * microbar* to click like achivment talents so on so on when i pressed it it closes it self instantly so i cant get to microbar intime before it closes on it self is there and issue from my side or?

**Version Number**
1.3.108-Release   7.3.5 game version

**Steps to Reproduce**
1. Step 1 - press the menu button
2. Step 2 - move the mouse to click on the any of the bars thing
3. Step 3 - watch it disapear for no reason

**Expected Behavior**
i hoped it would stay up so i can click on it instad of instantly disapear for me

**Actual Behavior**
it should stay up intill i click anything

**Only DiabolicUI Enabled**
like i said before it just disapears from me

**Additional Information**

**Error Log**

```

```

**Comment by christhewarlock** [comment]
it was messing up with another addon i had my bad

**Comment by goldpaw** [comment]
Plus it's supposed to work that way. It's like a dropdown, only it goes upwards! It remains visible as long as the mouse is hovering over the menu buttons or any of the menu items, then disappears a few secs after you move the mouse away! 

Not a bug, it's a feature! :+1: ;)
