### ISSUE TITLE
German Objectives are displayed wrong

### ISSUE THREAD

**Issue by Thjodolf** [cogwerkz/DiabolicUI#118]
**Description**
In the german quest objectives (titles and objectives on the right side of the screen) every word starts with a capital letter and after every Umlaut is a capital letter.

**Version Number**
1.3.108

**Steps to Reproduce**

1. Step: Start WoW with german language
2. Step: Add a Quest with Umlauts to the Objectives

**Expected Behavior**
German Quest Title and Objective Text should be displayed correct. 
Example: Quest Id: 13636
Quest Title: "Befehle für Sturmlanze"
Objective: "Bringt die Befehle für Sturmlanze zu Gebirgsjäger Sturmlanze in der Station Algaz."

**Actual Behavior**
German Quest Title and Objective are always written with a capital letter after every Umlaut and every word starts with a capital letter. Wrong letters are shown bold in the example.
Example: Quest Id: 13636
Quest Title: "Befehle **F**ü**R** Sturmlanze"
Objective: "Bringt **D**ie Befehle **F**ü**R** Sturmlanze **Z**u Gebirgsjä**G**er Sturmlanze **I**n **D**er Station Algaz."

**Only DiabolicUI Enabled**
Only happens in DiabolicUI

**Additional Information**
None

**Error Log**
None

**Comment by goldpaw** [comment]
Yeah, I did the caos for visual mmo-like purposes, but totally forgot capital letters have a bit more importance in German. Should pretty much just be nouns and names, right? I'll get it fixed, I'll leave the texts as they are for the deDE locale! :+1:

**Comment by Thjodolf** [comment]
Hi goldpaw. Thanks for the quick and nice reply. Yes, it's nouns and names. I appreciate that you are going to fix this minor issue.

Your UI is really well designed and it's so rare to see a good looking UI. Most UIs are only focusing on functionality and look ugly. 
Keep up the good work.

**Comment by goldpaw** [comment]
Fixed a while back, forgot to close.
