### ISSUE TITLE
Group Frames

### ISSUE THREAD

**Issue by goldpaw** [cogwerkz/DiabolicUI#12]
The UI needs group frames. Simple as that. 

Should be kept simple, minimalistic, unintrusive, yet easy to track and click for healers, tanks, and so on. 

Might be an idea to keep them more grid-like and avoid heavy graphics here, to better allow for user customization since this is the one thing pretty much everybody has a different preference for. And the huge group frames in Diablo are completely useless in a WoW context, so we need to go our own way here.

**Comment by AntonyMcLovin** [comment]
Is it possible to activate and  also deactivate the upcomming group frames? As a healer I always use grid/vuhdoo so no grp frames needed for a lot of healer I think.

**Comment by Maizna** [comment]
would be nice to have them kept simple. but i hope you still make them look diablo style :)

**Comment by GRscorpio** [comment]
any news update for group frames?

**Comment by goldpaw** [comment]
Since Grid, the default Blizzard frames and several others fit very nicely with this UI, I've decided to not add group frames. I might change this decision in the future, but for now I have no plans of doing it. This UI also work fine with Goldpaw's GroupFrames, just to have that mentioned.
