### ISSUE TITLE
Repetition on pet image

### ISSUE THREAD

**Issue by G3ls0n** [cogwerkz/DiabolicUI#22]
Had not seen that already had a topic on the group, then just to not let repeated I will modify kkkkkk.

The animation of the helpers this with a dry cut, nothin' else to spoil just to not leave the topic the same even

**Comment by goldpaw** [comment]
Well I'm totally confused at least, that's for sure! If the original issue was the lack of group frames, I'm on that! :) :+1: 

In Legion I think the Blizzard raid frames should still be working fine, and in all versions it's possible (at least until I come up with something more fitting) to use other raid frame addons like Grid.  And, I even think the raid frames from my other UI can function with this one. Try using Goldpaw's GroupFrames (and it's dependency Goldpaw's UI Core) from Curse/GitHub as raid frames:

https://mods.curse.com/addons/wow/gui4_groupframes
https://mods.curse.com/addons/wow/gui4

No idea what repetition on pet image refers to, though. :)

**Comment by goldpaw** [comment]
Since 3d portrait animations are a blizzard thing, it's not really something I can affect.
