### ISSUE TITLE
Target Bar

### ISSUE THREAD

**Issue by Syntharia** [cogwerkz/DiabolicUI#23]
Is there anyway to add that we can move the target bar around. I personally like playing with my target bar at the bottom of the screen above my action bars so being able to move that bar would be an awesome option.

**Comment by AntonyMcLovin** [comment]
not only the target bar. Also the bars in general? Like the stance bar, or the cast bar or the special spell bar for bosses like Guldan (at the very bottom left)? Needs to be at another place for raiding ;)

**Comment by goldpaw** [comment]
Not going to be making anything movable in this UI, though I intend to release parts of it as standalone addons, and those WILL have movable items.
