### ISSUE TITLE
Wrong procs Hunter

### ISSUE THREAD

**Issue by Laiev** [cogwerkz/DiabolicUI#24]
I was playing on my hunter and everytime one of my proc happen, the wrong ability highlight.

![screenshot_5](https://cloud.githubusercontent.com/assets/9333755/23236637/b55ec0b6-f938-11e6-81cb-61427847873a.png)

The proc on the screen is for Sidewinders not Aimed Shot, sometimes (rarely to be honest) the proc is right, but most of time it highlight the wrong ability

**Comment by goldpaw** [comment]
Ouch. Totally not intended. :o

**Comment by goldpaw** [comment]
should be fixed in 1.1.32, was a result of some delayed updates to the spell overlay displays.
