### ISSUE TITLE
Buff timer bar unaligned

### ISSUE THREAD

**Issue by Laiev** [cogwerkz/DiabolicUI#25]
I can't replicate it, but the buff (and debuff) timer bar was unaligned with the icon itself, after a /reload it fixed and never happened again but unsure if will happen sometime again.

![screenshot_4](https://cloud.githubusercontent.com/assets/9333755/23236832/93783e7c-f939-11e6-9a56-f6f9ecd1fb9a.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/9333755/23236855/accf055e-f939-11e6-88e3-5364cc967e90.png)

No, the /reload didn't fix it

**Comment by goldpaw** [comment]
That's strange. Do you have any other addons that work with buffs, buff or cooldown timers or such that might interfere? If it's an incompatibility I can surely fix it, just need to know where to start looking. :) 

In my code timers are positioned once - at creation - and never moved. So either there's a bug in my code (which I'll ofc look for), or some other addon is modifying things. Which I'll try to work around even if we can't identify it. 

Anyway, try with only my UI and no other addons first. If it doesn't happen then, then I at least now where to start looking. :)

**Comment by Laiev** [comment]
I tested turning off everything except ui, and turning on one by one, and can't replicate (maybe because /reload fix it), it's really confusing since there's no pattern and I use no addon for buffs (except if some of my addons do something with buffs and they don't describe it). For me it's more like /reload fix it because maybe the order of load of each addon is different from the order of load in starting game, so following this logic it's a addon incompatibility.
