### ISSUE TITLE
Clicking a quest title in the quest tracker opens the quest below it instead

### ISSUE THREAD

**Issue by goldpaw** [cogwerkz/DiabolicUI#29]
This bugs seems to occur in Legion only, waiting for a bit more feedback on what types of quests it happens with.

**Comment by AntonyMcLovin** [comment]
When you do mythic + dungeons the quest tracker doesnt appear. I dont see any time left and the affixes. Also when you start the timerun a bar-frame appears in the middle of the screen. Maybe this should be the time left? But nothing happens with it. Should be a bug either way.
