### ISSUE TITLE
Quest tracker itembuttons bug out 

### ISSUE THREAD

**Issue by AntonyMcLovin** [cogwerkz/DiabolicUI#34]
Message: ...ace\AddOns\DiabolicUI\modules\objectives\tracker.lua:638: attempt to index field 'border' (a nil value)
Time: 03/01/17 11:46:57
Count: 38
Stack: [C]: ?
...ace\AddOns\DiabolicUI\modules\objectives\tracker.lua:638: in function `AddQuestItem'
...ace\AddOns\DiabolicUI\modules\objectives\tracker.lua:822: in function `SetQuestItem'
...ace\AddOns\DiabolicUI\modules\objectives\tracker.lua:1022: in function `Update'
...ace\AddOns\DiabolicUI\modules\objectives\tracker.lua:1416: in function `UpdateTracker'
...ace\AddOns\DiabolicUI\modules\objectives\tracker.lua:1396: in function `ParseQuests'
...ace\AddOns\DiabolicUI\modules\objectives\tracker.lua:1652: in function `?'
Interface\AddOns\DiabolicUI\engine\engine-core.lua:344: in function <Interface\AddOns\DiabolicUI\engine\engine-core.lua:272>

Locals: 

Message: ...ace\AddOns\DiabolicUI\modules\objectives\tracker.lua:638: attempt to index field 'border' (a nil value)
Time: 03/01/17 11:46:43
Count: 2
Stack: [C]: ?
...ace\AddOns\DiabolicUI\modules\objectives\tracker.lua:638: in function `AddQuestItem'
...ace\AddOns\DiabolicUI\modules\objectives\tracker.lua:822: in function `SetQuestItem'
...ace\AddOns\DiabolicUI\modules\objectives\tracker.lua:1022: in function `Update'
...ace\AddOns\DiabolicUI\modules\objectives\tracker.lua:1416: in function `UpdateTracker'
...ace\AddOns\DiabolicUI\modules\objectives\tracker.lua:1396: in function `ParseQuests'
...ace\AddOns\DiabolicUI\modules\objectives\tracker.lua:1658: in function `ForceUpdate'
...ace\AddOns\DiabolicUI\modules\objectives\tracker.lua:1833: in function <...ace\AddOns\DiabolicUI\modules\objectives\tracker.lua:1833>
[C]: ?
[C]: in function `Hide'
Interface\FrameXML\UIParent.lua:2358: in function `SetUIPanel'
Interface\FrameXML\UIParent.lua:2385: in function `MoveUIPanel'
Interface\FrameXML\UIParent.lua:2416: in function `HideUIPanel'
Interface\FrameXML\UIParent.lua:2090: in function <Interface\FrameXML\UIParent.lua:2082>
[C]: in function `SetAttribute'
Interface\FrameXML\UIParent.lua:2884: in function <Interface\FrameXML\UIParent.lua:2871>
[C]: in function `HideUIPanel'
Interface\FrameXML\UIParent.lua:2850: in function `ToggleFrame'
Interface\FrameXML\WorldMapFrame.lua:242: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals:

**Comment by goldpaw** [comment]
fixed in 1.1.30
