### ISSUE TITLE
bar in the middle of the screen without purpose | no mythic + affixes shown

### ISSUE THREAD

**Issue by AntonyMcLovin** [cogwerkz/DiabolicUI#38]
Hi there, 

i commented on this several times. 
See Screenshot: 
https://picload.org/image/rloilgga/wowscrnshot_030717_101659.jpg

It always appears, when starting mythic + dungeon... 

Also the affixes of mythic + dungeons are not shown anywhere. Only the regular world quests are tracked: 
See second Screenshot: 
https://picload.org/image/rloilgdw/wowscrnshot_030717_100418.jpg

**Comment by goldpaw** [comment]
bar bug fixed. Tracker for mythic affixes is on my todo list, as a separate issue.
