### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by snapplesaucy** [cogwerkz/DiabolicUI#41]
It wont stay off either, the error message keeps popping up ever few seconds between hitting "close" reloading ui didnt work either.

Message: Interface\AddOns\DiabolicUI\engine\engine-core.lua:1655: attempt to perform arithmetic on local 'screenHeight' (a nil value)
Time: 03/18/17 19:49:39
Count: 24
Stack: Interface\AddOns\DiabolicUI\engine\engine-core.lua:1655: in function `GetSizeOfPixel'
...dOns\DiabolicUI\modules\unitframes\elements\aura.lua:96: in function <...dOns\DiabolicUI\modules\unitframes\elements\aura.lua:95>
...dOns\DiabolicUI\modules\unitframes\elements\aura.lua:403: in function <...dOns\DiabolicUI\modules\unitframes\elements\aura.lua:397>
...dOns\DiabolicUI\modules\unitframes\elements\aura.lua:785: in function `?'
Interface\AddOns\DiabolicUI\handlers\unitframe.lua:140: in function <Interface\AddOns\DiabolicUI\handlers\unitframe.lua:132>

Locals: self = <unnamed> {
 0 = <userdata>
 GetScreenSize = <function> defined @Interface\AddOns\DiabolicUI\engine\engine-core.lua:1550
 SetPixelSize = <function> defined @Interface\AddOns\DiabolicUI\engine\engine-core.lua:1628
 Execute = <function> defined @Interface\FrameXML\SecureHandlers.lua:699
 UnwrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:710
 GetSizeOfPixel = <function> defined @Interface\AddOns\DiabolicUI\engine\engine-core.lua:1653
 GetResolution = <function> defined @Interface\AddOns\DiabolicUI\engine\engine-core.lua:1526
 WrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:704
 GetPixelScale = <function> defined @Interface\AddOns\DiabolicUI\engine\engine-core.lua:1623
 SetPixelScale = <function> defined @Interface\AddOns\DiabolicUI\engine\engine-core.lua:1640
 SetFrameRef = <function> defined @Interface\FrameXML\SecureHandlers.lua:715
 GetPixelSize = <function> defined @Interface\AddOns\DiabolicUI\engine\engine-core.lua:1616
}
screenWidth = nil
screenHeight = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = 1
(*temporary) = "attempt to perform arithmetic on local 'screenHeight' (a nil value)"
HD_MODIFIER = 1

**Comment by goldpaw** [comment]
fixed
