### ISSUE TITLE
I can not move the spells on the panel.

### ISSUE THREAD

**Issue by Samridigan** [cogwerkz/DiabolicUI#43]
I can not move the spells on the panel.
Maybe I just do not understand what the essence is or do not really have such an opportunity now?
Oh, yes, another chat window always resets the settings.

**Comment by goldpaw** [comment]
Hold down ctrl alt and delete while dragging spells. It's mentioned in the bottom of the actionbar setup window too. :)  I assume you figured it out yourself, but leaving this comment here in case somebody else comes here looking for this answer! :)
