### ISSUE TITLE
Brewmaster Monk stagger bar

### ISSUE THREAD

**Issue by wcronin17** [cogwerkz/DiabolicUI#44]
Currently no way to monitor your stagger as a brewmaster monk with this UI. Would be nice to replace the mana portion of the split bar since there is no use for it in brewmaster spec and input the stagger amount.

**Comment by goldpaw** [comment]
Hm. Maybe not a bad idea. :)

**Comment by goldpaw** [comment]
This is included in issue #18 so I'm closing this as a duplicate
