### ISSUE TITLE
Minimap not looking correct

### ISSUE THREAD

**Issue by Maizna** [cogwerkz/DiabolicUI#46]
i posted this in the warmane/addons/DiabolicUI forum (picture included). my minimap is not looking like in your screenshots, its just a big square/half transparent map. 
No other map addons have been used, just diabolicui

**Comment by AntonyMcLovin** [comment]
There is no bug. The Minimap has changes diabolo style ;) Also, you should post everything here.

**Comment by Maizna** [comment]
as i wrote in my above post: no, the minimap does not look diablo style. if you wanna see how it looks check this out: http://de.tinypic.com/r/i3bdzr/9

This is how the minimap looks in my game. no ither addons installed

**Comment by goldpaw** [comment]
That's how it's supposed to look. Like the Diablo III minimap. I explained it in the patchnotes for DiabolicUI 1.1 when I released that on February 19th 2017. The change is intended. I have removed and replaced the old screenshot on Curse. 👍 

Changelog: 
https://github.com/cogwerkz/DiabolicUI/blob/master/CHANGELOG.md#1122-2017-02-19
