### ISSUE TITLE
7.2.5 Bug chat bubbles

### ISSUE THREAD

**Issue by AntonyMcLovin** [cogwerkz/DiabolicUI#48]
Hi there, 

with the new 7.2.5 release of the game everytime I'am in a dungeon and a npc speaks I get an error which does not stop. As You can see at the moment I'm at 77700 errors ^^ Also the bubbles have the blizzard style after  I get this error. 

Message: Interface\AddOns\DiabolicUI\modules\chat\bubbles.lua:58: Attempt to access forbidden object from code tainted by an AddOn
Time: 06/16/17 11:02:49
Count: 77700
Stack: Interface\AddOns\DiabolicUI\modules\chat\bubbles.lua:58: Attempt to access forbidden object from code tainted by an AddOnInterface\SharedXML\SharedBasicControls.lua:204: in function `origErrorHandler'
...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:317: in function <...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:300>
[C]: ?
[C]: in function `GetName'
Interface\AddOns\DiabolicUI\modules\chat\bubbles.lua:58: in function `IsBubble'
Interface\AddOns\DiabolicUI\modules\chat\bubbles.lua:73: in function <Interface\AddOns\DiabolicUI\modules\chat\bubbles.lua:68>

Locals: errorMessage = "Interface\AddOns\DiabolicUI\modules\chat\bubbles.lua:58: Attempt to access forbidden object from code tainted by an AddOn"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:187
MESSAGE_TYPE_ERROR = 0

**Comment by goldpaw** [comment]
This will be fixed in the upcoming 1.2 release of DiabolicUI. It's actually a 7.2.0 bug related to how Blizzard creates nameplates of friendly NPCs within instances. I will try to hurry up the 1.2 update a bit :)
