### ISSUE TITLE
Resource bubble for paladins

### ISSUE THREAD

**Issue by dswagz** [cogwerkz/DiabolicUI#5]
Is  there any way you can split the resource bar like demon hunters in diablo? we have both mana and holy power, this would be amazing.

I am trying to locate settings to possibly do it myself but it looks like there are no interface settings in game, just the lua files?

any response is appreciated.

Cheers,
DSwagz

ps. I LOVE THIS ADDON <3

**Comment by goldpaw** [comment]
This will be included in the 1.1 beta of DiabolicUI which I'll make public in the near future. All classes that have both mana and another primary resource like feral druids, balance druids, shamans, paladins and probably more will have split orbs, just like in Diablo.
