### ISSUE TITLE
Missing DK runes and % bar for some quests and  worldquests

### ISSUE THREAD

**Issue by maqarzan** [cogwerkz/DiabolicUI#51]
Hi!
Runes bar for DK's is missing ( annoying af ), and percentage bar for worldquest.
Please fix it :) Great UI btw :))

**Comment by goldpaw** [comment]
DK runes (and all other 3rd class resources as there is a separate issue about here) will be added in 1.3, which I have in private testing right now. World Quests show percentages from 1.2. :)
