### ISSUE TITLE
Quest tracker incompatible with WQGF

### ISSUE THREAD

**Issue by ProfessionalGeek** [cogwerkz/DiabolicUI#52]
**Description**
Unfortunately, [WQGF](https://mods.curse.com/addons/wow/worldquestgroupfinder) doesn't seem to function with the latest version of DiabolicUI.
Disabling the quest tracker allows WQGF to function normally again.

This is obviously due to the new objectives tracker, I am hoping there is a solution to be able to use both the new objectives frames and WQGF.

**Version Number**
WQGF: v0.26.3
DiabolicUI: v1.2.38

**Steps to Reproduce**

1. Install both WQGF and DiabolicUI
2. Run game. Notice that DiabloicUI quest tracker works just fine, but all functionality of WQGF no longer operates.
3. Disable DiablolicUI quest tracker by renaming `/modules/objectives/` folder, reload / relog.
4. Note that WQGF functions flawlessly.

**Expected Behavior**

Since WQGF does not replace the quest tracker, I assumed it would work with any mod that may.
Tested WQGF with DiabloicUI and it does not function.
Tested with [another addon that completely replaced the objectives frames](https://mods.curse.com/addons/wow/255976-eska-quest-tracker) and found that it functions normally.

**Actual Behavior**

With Eska (the other addon that completely replaces the objectives tracker), WQGF functioned normally.
With DiaobloicUI, WQGF does not function whatsoever.

**Only DiabolicUI Enabled**

**Additional Information**

I have made a report with the author of WQGF to see if they have any insight as well.

**Error Log**

```
No errors reported.
```

**Comment by goldpaw** [comment]
Support for WQGF will be included in the next update. :)

**Comment by ProfessionalGeek** [comment]
Thanks so much. Buy you a beer soon!
