### ISSUE TITLE
version 1.2.43 for the patch 7.2.0. Holly power

### ISSUE THREAD

**Issue by kelvines** [cogwerkz/DiabolicUI#53]
Hi! Can you, please, make last version of addon for patch 7.2.0. I can`t play without artifact power, and holy power. 
In short: version 1.2.43 for the patch 7.2.0.

Я обожаю ваш аддон, он очень красив, но пожалуйста, сделайте версию с holy power и artifact power for 7.2.0. Ящик пива этому господину!)

I also did not like the scaling of the interface in the version of adddon for 7.1.5. I had to change the engine files with the latest version of the addon.
The interface has become normal, stably works on 7.2.0, but still there is no light energy.

**Comment by Kkthnx** [comment]
@kelvines For future references/reports please use the template provided when making a bug report.

@goldpaw Is hard at work getting class power/resources together for each class. Please give him time to get this all sorted out and implemented into the UI. Thank you.

**Comment by goldpaw** [comment]
Artifact power is there for all versions now, and holy power has never been in the UI. It's under development along with all the other 3rd class resources like burning embers, chi, death knight runes and so on. I have no ETA; but it won't be long. :) 

But that has already been reported, and thus this is a duplicate issue! :)
