### ISSUE TITLE
Feature request: replace minimap tracking dots

### ISSUE THREAD

**Issue by dualcoding** [cogwerkz/DiabolicUI#55]
**Description**
In vanilla WoW, hunter tracking (humanoids in particular) is very messy: the dots are crowded and overlapping, and the difference between mobs and players is subtle and between resources and neutral mobs nonexistent. The larger minimap in DiabolicUI helps with the crowding, but something like Chinchilla minimap's "Nandini New" icons would be great.

Running Chinchilla along with Diabolic works fine so no big deal, but still would be nice :)
![2017-07-11 1](https://user-images.githubusercontent.com/3287990/28065353-7ddb8f62-6638-11e7-8763-5a0114d0a9c0.png)
![2017-07-11 2](https://user-images.githubusercontent.com/3287990/28065362-847bc17a-6638-11e7-936d-1061fc6c1d5a.png)

**Comment by goldpaw** [comment]
That looks awesome! Definitely going to be adding something like that. :) 👍

**Comment by dualcoding** [comment]
Awesome :)
