### ISSUE TITLE
Draenor Zone Abilities have their cooldown spiral fill the whole screen! 

### ISSUE THREAD

**Issue by Gambit577** [cogwerkz/DiabolicUI#56]
**Description**
Love the UI but was wondering if there was a way to turn off the clockwise cooldown fader on the fullscreen?

**Version Number**
1.2.45

**Steps to Reproduce**

1. Step 1
2. Step 2
3. Step 3
4. Step 4

**Expected Behavior**

**Actual Behavior**

**Only DiabolicUI Enabled**

**Additional Information**

**Error Log**

```

```

**Comment by goldpaw** [comment]
Cooldown fader on fullscreen? I have no idea what you're referring to. Do you have a screenshot? :)

**Comment by rkuenzel** [comment]
I reported the same thing in Discord (@Wehwehchen in #bug_reports, 2017-07-15, 21:06):

DiabolicUI: In the garrison — and most likely in all Draenor areas where you have a zone ability — if you do not have the zone ability assigned to an actionbar button, then the "global cooldown spiral" is displayed over the whole screen. This seems to be caused somehow by the re-styling of the ZoneAbilityFrame (in your modules\actionbars\elements\floaters.lua:94). Looks quite nice, but drives me crazy :wink:

**Comment by goldpaw** [comment]
Ouch. Not intended. :)

**Comment by Gambit577** [comment]
I'd have to video cap it. It literally does a cd clockwise fade around the whole screen.

**Comment by Gambit577** [comment]
And it's happening in legion zones. From regular attacks.

**Comment by goldpaw** [comment]
I've found the bug and fixed it, and it'll be updated later today. :) 👍
