### ISSUE TITLE
Feature proposal: larger icons for crowd control on top of nameplates

### ISSUE THREAD

**Issue by dualcoding** [cogwerkz/DiabolicUI#62]
**Description**

All auras are equal, but some auras are more equal than others.

It is important to keep track of crowd control on players in PvP. There are a few reasons why showing this prominently on top of nameplates can be useful:
- CC does have visual cues in the game world, but usually over the head and so often partially covered by nameplates.
- Keeping track of CC that breaks on damage becomes much easier in uncoordinated PvP.
- Having a number on the remaining duration makes it easier to keep track of DR, when the CC is about to expire, and if a player uses a trinket or ability to break out early.
- Additionally, when nameplates are set to clamp to the screen edges you can keep track of a player not currently in your view.

Example running on a local branch:
![2017-07-24 7](https://user-images.githubusercontent.com/3287990/28568576-a369e8ba-7136-11e7-9277-cce5a32d09e4.png)
(ignore the duplicated auras, obviously they shouldn't be shown in so many places)

This is a fairly large visual decision, but if you're interested I'm willing to attempt a clean implementation.

**Comment by goldpaw** [comment]
This looks so cool I'm actually interested in doing it myself, if you don't mind! Not to be a dick and steal your thunder or anything, this just really sparked my interest! It's a great idea! :D 

Been thinking about implementing something similar for the unitframes too. A large aura displayed on the middle of them for dispellable debuffs, important boss debuffs and so on. Not that there's many unitframes to do that on currently, but I've got a new focusframe in the works, and it'd surely come in handy there. To put it short I'm removing the focus frame from the corner, plus giving it the same look as the ToT frame, more or less.

**Comment by dualcoding** [comment]
Haha, I don't mind at all! Glad you like it :)
Great idea about aura displays too. The original itch I wanted to scratch was actually making important auras more visible in general. I played around with different size auras for the player frame, but never got it to feel quite right.

The current focusframe looks absolutely great, but the ToT is easier to read, so probably a good change there.

For the record I will generally not have spent a lot of effort on anything before pitching it to you, it's your project after all! So if you want to veto something or do it yourself I certainly won't mind. I'll just find another itch to scratch. Hmm, maybe I'll prototype group frames next... ;)

**Comment by goldpaw** [comment]
Hehe, I can't promise I'll create everything you scratch, so control your itches... ;)   Having that said, remember that my design philosophy in DiabolicUI includes NOT being configurable. Everything should be within the reach of 2 clicks. And everything should be possible to do whenever, and not just when "not engaged in combat".

**Comment by goldpaw** [comment]
Because after all, it's all about user experience (UX), not about a skinned interface (UI).
