### ISSUE TITLE
How can i disable or resize the minimap?

### ISSUE THREAD

**Issue by Bondrail** [cogwerkz/DiabolicUI#65]
**Description**

I noticed changing the coding of the minimap.iua for size in the settings folder does not change the size. It is very large. Or is there a way to disable it so I can use a different map all together?

**Version Number**

version for 7.2.5

**Steps to Reproduce**

1. Step 1 
2. Step 2
3. Step 3
4. Step 4

**Expected Behavior**

I changed multiple numbers in the minimap.iua and none of them seem to change the size of the map. I went back and forth between numbers and nothing. Or am I changing the wrong file?

**Actual Behavior**

**Only DiabolicUI Enabled**

I only had DiabolicUI installed at the time.

**Additional Information**
I just would like to know what numbers to change. Because it is making me not want to use this beautiful ui. I really like the older model of the map. Not this huge map. I am playing on a smaller laptop.

**Error Log**

```

```

**Comment by Bondrail** [comment]
Wow! I finally resized it. I had to go into the negative 100s to get it smaller. So I had go from 10 to -100. But I finally got it.

**Comment by goldpaw** [comment]
Not exactly sure what you changed, but it doesn't sound like the "right" thing. No such thing as a negative size in WoW. Out of curiosity, which file and which line do you change? :)

**Comment by Bondrail** [comment]
I changed this section and it worked beautifully. But I had to go way in the negatives.  The original size was 10 now its at -100. I really think your work is awesome. Thank you.
Engine:NewStaticConfig("Minimap", {
	size = { MINIMAP_SIZE, MINIMAP_SIZE }, 
	point = { "TOPRIGHT", "UICenter", "TOPRIGHT", -20, -64 }, -- -20, -50
	map = {
		size = { MINIMAP_SIZE + -100, MINIMAP_SIZE + -100 }, 
		point = { "TOPLEFT", 100, 5 },
		mask = path..[[textures\DiabolicUI_Minimap_316x316_Mask.tga]]

**Comment by goldpaw** [comment]
Ah. That's not the size. The size was the value of the variable MINIMAP_SIZE plus 10. The value of MINIMAP_SIZE is set in the file DiabolicUI\data\constants.lua in line 24. If you change it there instead, other modules relying on that variable for their positioning will be updated too. :) 

Oh, and you don't have to write "+ -100". It'll be enough with "-100" in those places. ;)

**Comment by Bondrail** [comment]
I have another question. Have you put in combo points, chi, burning embers and such yet? I saw the coding for them but they don't seem to show. I am excited to see this addon grow :)

**Comment by Bondrail** [comment]
Oh ok. I was in the wrong file. I recoded it back to the original and went into the constants.lua and did it there. Thank you soo much for pointing me in the right direction.

**Comment by goldpaw** [comment]
On the issue of combo points and such; not yet! There are other addons that can provide some fairly nice looking ones until my more modest stuff is done, though. I haven't tested it myself, but the one called "Engraved" looks fairly nice. 

https://mods.curse.com/addons/wow/engraved

**Comment by Bondrail** [comment]
I thought that was it since I saw the coding for them. I am looking forward to the finished UI. I like how you made it simple. And thank you for the suggestion for the Engraved mod. That will do till yours are complete.

**Comment by StygianTheBest** [comment]
Changing the variable in constants does not change the map frame size, it just changes the map size within the frame. Maybe you can borrow some ideas from SexyMap and make it configurable.
