### ISSUE TITLE
Quest completion % bar

### ISSUE THREAD

**Issue by dswagz** [cogwerkz/DiabolicUI#68]
**Description**

The bar that pops up while you are completing a quest that requires you to do X amount of tasks to complete a % bar /100%, does not show up.

For example, world quest that require you to do things in a certain area, and each thing adds to a progress bar. The quest completes when you hit 100%. This bar does not show up.

**Version Number**

7.2, 7.2.5, 7.3

**Steps to Reproduce**

1. Step 1 Start a quest that requires you to kill a bunch of mobs to fill a % bar.
2. Step 2 ???
3. Step 3 Profit
4. Step 4 !!!

**Expected Behavior**

There should be a bar that pops up that shows you how close you are to completing the quest X%/100%

**Actual Behavior**

Nothing

**Only DiabolicUI Enabled**

**Additional Information**

**Error Log**

```

```

**Comment by goldpaw** [comment]
Not a bar, but a completion percentage is shown. So it's not missing, it's just not represented in the form of a bar. It's numbers.
