### ISSUE TITLE
Minimap icons?

### ISSUE THREAD

**Issue by dswagz** [cogwerkz/DiabolicUI#69]
**Description**

Minimap icons show up in the middle of the map because of how large it is.

**Version Number**

7.25, 7.3

**Steps to Reproduce**

1. Step 1 look at the minimap and see the tiny icons
2. Step 2
3. Step 3
4. Step 4

**Expected Behavior**

The icons should be around the edges of the map.

**Actual Behavior**

They are in the middle of the map

**Only DiabolicUI Enabled**

**Additional Information**

**Error Log**

```

```

**Comment by goldpaw** [comment]
Minimap icons are hidden by default, and the addon [MBB](http://www.curse.com/addons/wow/mbb) is needed to show them. This is linked in the suggestion addons part of the description.
