### ISSUE TITLE
Minimap Icons Mismatching

### ISSUE THREAD

**Issue by falcophoenix** [cogwerkz/DiabolicUI#70]
**Description**
The minimap icons for quests markers/mailboxes ect are completely different from the normal indicator icons.

**Version Number**
1.3.61

**Steps to Reproduce**

1. Only Diabolic UI enabled
2. Proper map icons enabled in tracker

**Expected Behavior**
Quest giver icons should be gold punctuations, mailbox icons should be envelopes, ect.

**Actual Behavior**
Quest giver icons are pet battle green paws, mailboxes are blue question marks, other mismatches

**Only DiabolicUI Enabled**

**Additional Information**

**Error Log**

```

```

**Comment by goldpaw** [comment]
Oh balls, they changed the icon order again with 7.3? 
I'll get on it!

**Comment by goldpaw** [comment]
Fixed in 1.3.62-Release.
