### ISSUE TITLE
Minimap button bag buttons appear behind minimap

### ISSUE THREAD

**Issue by JBurlison** [cogwerkz/DiabolicUI#73]
**Description**
Weh you click the + in the upper right hand corner of the mini map, the icons expand under the minimap.

**Version Number**
1.3.62

![wowscrnshot_083117_061706](https://user-images.githubusercontent.com/1290966/29918741-97e5ea02-8e14-11e7-984c-e02dc6a286d5.jpg)

**Comment by goldpaw** [comment]
Ouch :o

**Comment by goldpaw** [comment]
Fixed in 1.3.63

**Comment by mindogo1** [comment]
Still going on :(

![image](https://user-images.githubusercontent.com/32150876/30675741-d619bf5c-9e8a-11e7-9f09-614d386f76ab.png)

**Comment by ProfessionalGeek** [comment]
This is easily remedied by right-clicking the **+** button, and setting the **MBB** options to grow up (by 1) and then to the left. This will place everything perfectly.
