### ISSUE TITLE
Lua Error to my menu

### ISSUE THREAD

**Issue by Reignqt** [cogwerkz/DiabolicUI#74]
Message: ...ts\libs\AceGUI-3.0\widgets\AceGUIWidget-DropDown.lua:384: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Time: 08/31/17 19:56:27
Count: 1
Stack: ...ts\libs\AceGUI-3.0\widgets\AceGUIWidget-DropDown.lua:384: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
[C]: ?
[C]: ?
...ts\libs\AceGUI-3.0\widgets\AceGUIWidget-DropDown.lua:384: in function <...ts\libs\AceGUI-3.0\widgets\AceGUIWidget-DropDown.lua:382>

Locals:

**Comment by goldpaw** [comment]
This isn't a DiabolicUI error, but from another addon. 

In patch 7.3 blizzard changed how the command PlaySound works. The libraries in Ace3 which are used by many addons, didn't updated this, so a lot of addons broke as a result. The error linked is an Ace3 error. And DiabolicUI does not use Ace3.
