### ISSUE TITLE
Quest item

### ISSUE THREAD

**Issue by De1v** [cogwerkz/DiabolicUI#77]
Hey Mate.  Is it possible to make a quest item as in default blizzard UI. When it pops next to the quest in right side?

**Comment by goldpaw** [comment]
Quest item buttons should appear in the quest tracker. The tracker shows quests in the current zone. 

If it's not working, please tell me which version of WoW you're on, and what level and class you're playing so I can try to reproduce the problem here.

**Comment by goldpaw** [comment]
Updated a lot of the tracker functionality in 1.3.97, so I'm closing all currently open issues on this.
