### ISSUE TITLE
No group frames & World Quest tracker on the UI

### ISSUE THREAD

**Issue by Nikki1993** [cogwerkz/DiabolicUI#78]
I run 2560x1080 resolution and when I use just the UI (all other addons disabled) this is what I see

![image](https://user-images.githubusercontent.com/1446529/30340459-3f48031c-97fb-11e7-8261-db23e0a68bb5.png)

Notice, I am in the group but no frames for the party members.

Same happens with world quests. They go way beyond the screen.

**Comment by Nikki1993** [comment]
I believe this is caused by the resolution, as you can see the minimap is also quite close the the center instead of being top right corner.

**Comment by goldpaw** [comment]
Yes, I know the exact cause of this. The UI is running in 16:19, while you have a wider aspect ratio than that. 

I'll fix it in the next update. :)

**Comment by goldpaw** [comment]
Oh, the party frames aren't included in this UI yet. The solution (for now) is to enable the use of the compact raid frames as party frames, this is done in the Raid Profiles portion of the blizzard interface options menu.

**Comment by Nikki1993** [comment]
Yay, can't wait o/ otherwise have to use default Blizzard UI for now due to elements being off the screen :(

**Comment by goldpaw** [comment]
This might sound like a stupid question, but are you running in windowed fullscreen, with the resolution in the slider set to 1920x1080? If so, go to "normal" fullscreen, set it to 2560x1080, then return to windowed fullscreen, relog and see what happens.

**Comment by yel-yel** [comment]
I have the same issue for the party frames, although my minimap is properly aligned. 
![2017-09-14](https://user-images.githubusercontent.com/31956605/30426149-3496b034-994b-11e7-9da7-229191febd27.png)
15" laptop with full screen 1920x1080. resolved it now by using raid frames, would love to use the proper party frames though!

**Comment by Nikki1993** [comment]
@goldpaw hm, last time I checked it was windows fullscreen on 2560x1080 but I will do your suggestion and see if it affects anything this evening.

**Comment by Nikki1993** [comment]
@goldpaw Oh, so you were right it was indeed set to 1920x1080 even though I used borderless windowed mode at 2560x1080.

That still begs the question why something like Elvui correctly scales, yet Diablo UI doesn't?

**Comment by Kkthnx** [comment]
@Nikki1993 Simple as this.

Different code, different UIs. The code can always be improved. Just because ElvUI works differently for you Vs this UI doesn't make it better in any means. Its just different.

**Comment by Nikki1993** [comment]
@Kkthnx no kidding...

I appreciate the gesture of support but no worries, I am web dev myself so I get it different code bla bla bla. This was more of an open question like hint to the dev, maybe something is broken with the scaling or scaling detection is wrong and needs improvement, perhaps take a look at how Elvui does it. In my opinion it days a lot of things right and is better. (but we are not talking opinion here).

I apologize if I come out as rude but a lot of people simply comment for the sake of commenting. I already knew what is a problem in the general sense (as you described).

**Comment by Kkthnx** [comment]
Goldpaw takes a different view on his code. More way secure and taint-free and more in-depth than ElvUI or Tukui or any UI at that. You didn't come out as rude, I just hadn't had my coffee yet! As a developer coffee is important <3

**Comment by goldpaw** [comment]
Just to let everybody know, I'm working on an update to the scaling features. Should all be good soon. :) 

When it comes to party frames though, I have no ETA. Going to add them, but for now I recommend using the compact raid frames as party frames too. Or another addon like Grid to handle group frames.

**Comment by goldpaw** [comment]
I'm closing this thread, not because everything has been fixed or I'm not working on it anymore, but because it contains at least 3 separate issues with all have different issues here assigned to them already. One issue per issue, please! ;)
