### ISSUE TITLE
Lua Error with brewfest quest

### ISSUE THREAD

**Issue by Luellin** [cogwerkz/DiabolicUI#79]
**Description**
Hi! i get the error with this brewfest quest [Bark for Drohn's Distillery!](http://www.wowhead.com/quest=11407/bark-for-drohns-distillery) or [Bark for T'chali's Voodoo Brewery!](http://www.wowhead.com/quest=11408/bark-for-tchalis-voodoo-brewery), And the error keep showing until i abandon the quest

**Version Number**
1.3.69

**Steps to Reproduce**
1. Step 1 Accept the brewfest quest 

**Only DiabolicUI Enabled**
Happened the same with only diabolic UI enabled

**Additional Information**

**Error Log**
Message: ...ace\AddOns\DiabolicUI\modules\objectives\tracker.lua:1697: bad argument #1 to 'string_match' (string expected, got nil)
Time: 09/27/17 00:05:16
Count: 16
Stack: ...ace\AddOns\DiabolicUI\modules\objectives\tracker.lua:1697: bad argument #1 to 'string_match' (string expected, got nil)
[C]: ?
[C]: ?
...ace\AddOns\DiabolicUI\modules\objectives\tracker.lua:1697: in function `GetQuestLogLeaderBoard'
...ace\AddOns\DiabolicUI\modules\objectives\tracker.lua:2352: in function `GatherQuestLogData'
...ace\AddOns\DiabolicUI\modules\objectives\tracker.lua:2611: in function `OnUpdate'
...ace\AddOns\DiabolicUI\modules\objectives\tracker.lua:2744: in function <...ace\AddOns\DiabolicUI\modules\objectives\tracker.lua:2744>

**Comment by goldpaw** [comment]
fixed in 1.3.70-Release, which will be live on Curse/Twitch soon'ish.
