### ISSUE TITLE
Stancebar Improvement

### ISSUE THREAD

**Issue by Anderzenn** [cogwerkz/DiabolicUI#91]
I think it could be awesome if right clicking the stancebar makes your turn back into your regular shape.
Like if you're a night elf it turns you back into a night elf when you right click it.

**Comment by goldpaw** [comment]
You mean right-clicking the stance bar button to cancel forms? Totally doable. I think. Hm.

**Comment by goldpaw** [comment]
Added changes that will cancel any "non-normal" form when the button is right clicked, while left clicking will toggle the stance bar as before. 

The tooltip also updates dynamically to show whether or not there is any form that can be cancelled by right clicking or not. 

This change will be included in the next update, probably tomorrow. Closing this suggestion.
