### ISSUE TITLE
Issues with quest tracker/quests

### ISSUE THREAD

**Issue by SAndgrid** [cogwerkz/DiabolicUI#94]
**Description**
Can't click on quests on quest tracker. 

**Version Number**
latest

**Steps to Reproduce**
1. Step 1
2. Step 2
3. Step 3
4. Step 4

**Expected Behavior**
Opens Quest Log with selected quest

**Actual Behavior**

**Only DiabolicUI Enabled**
No

**Additional Information**

**Error Log**

**Comment by goldpaw** [comment]
It opens the quest log for quests that have a log entry. Not world quests. Just "normal" quests.

**Comment by SAndgrid** [comment]
![image](https://user-images.githubusercontent.com/35510914/35019665-2ffc815c-fb39-11e7-9368-bde119c1b466.png)

**Comment by goldpaw** [comment]
The DiabolicUI tracker is set to show only quests in the currently visible map zone. It's also fully automatic, meaning we can't manually select which quests to show or not. 

If a quest in the current map zone don't show up it can be a couple of reasons. One of them that there's simply not enough room. Finished quests that are ready to be turned in are listed last, and it looks like the one you mentioned is finished. 

Could also be that the quest simply doesn't tell the UI which zone it is located in. In that case, the DiabolicUI tracker won't show it. Ever.

**Comment by SAndgrid** [comment]
if i edit this in \modules\objectives\
local emissaryQuestIDs = {
	[42170] = true, -- The Dreamweavers 
	[42233] = true, -- Highmountain Tribes
	[42234] = true, -- The Valarjar
	[42420] = true, -- Court of Farondis 
	[42421] = true, -- The Nightfallen 
	[42422] = true  -- The Wardens
}
will it be enough to switch off tracking world quests?
And thanks a lot for your work, the best WoW UI i have ever seen!

**Comment by goldpaw** [comment]
No, that won't remove them. 
I am however working on a way to split the world quests and normal quests, and make it possible to switch between them by clicking the tracker title. I have no ETA on when it's ready, but it's coming! :)

**Comment by SAndgrid** [comment]
Sounds great! Something really needed for people who just like questing or tired of doing world quests :)
Thanks a lot for your help!

**Comment by SAndgrid** [comment]
Ended a world quest to free some space. Still cant see the quest appearing in the quest tracker (Sentinel's final duty)
![image](https://user-images.githubusercontent.com/35510914/35020355-d3585c38-fb3c-11e7-850e-9a4ac02245ad.png)

**Comment by goldpaw** [comment]
I've updated the tracker to put profession quests and normal quests before the world quests. Should solve these issues for now. Marking this as closed.
