### ISSUE TITLE
Objectives Quest items not working, or stop working after a while!

### ISSUE THREAD

**Issue by Rukita** [cogwerkz/DiabolicUI#96]
**Description**

Hi, i love your UI, and i found an issue wich is that quest icon on the objectives painel doesn`t work. So we have to open the bags painel to click it and make the buff or wahtever work.

**Version Number**

1.3.94

**Steps to Reproduce**

1. Step 1The quest icon appears on the objectives painel
2. Step 2 We should operate it from there
3. Step 3 We click on the quest icon but it doesn`t work at all
4. Step 4

**Expected Behavior**

We should operate it from there

**Actual Behavior**

**Only DiabolicUI Enabled**

**Additional Information**

**Error Log**

```

```Thanx for the great job

**Comment by goldpaw** [comment]
I have noticed this myself. Trying to figure out when it happens and why. Working on it!

**Comment by Rukita** [comment]
Hi

Thx for your quick answer.
By this time im playing with your UI wich i realy like. 
Thx for the nice work you`r doing.

All the best


Enviado do Correio para Windows 10

De: Lars Norberg
Enviado: 1 de fevereiro de 2018 21:10
Para: cogwerkz/DiabolicUI
Cc: Rukita; Author
Assunto: Re: [cogwerkz/DiabolicUI] Objectives Quest items not working (#96)

I have noticed this myself. Trying to figure out when it happens and why. Working on it!

**Comment by goldpaw** [comment]
Hopefully this has improved in 1.3.97 which had a lot of tracker updates. If not, I'm still monitoring the situation.
