### ISSUE TITLE
World Quest Group Finder and World Quest tracker don't work anymore. 

### ISSUE THREAD

**Issue by maigonc** [cogwerkz/DiabolicUI#98]
**Description**
When I installed the addon DiabolicUI, the addon World Quest Group Finder stopped to work. For some reason, I'm not able to find groups.
Another addon World Quest tracker has the same functionality and it isn't working as well. Both add-ons have the functionality to find the group manually, clicking on the right side of the quest and this functionality doesn't work. Actually, the icon isn't there. 

**Version Number**
1.3.97-Release

**Steps to Reproduce**
1. Go to the World Quest area. 

**Expected Behavior**
1. Go to the World Quest area. 
2. Wait for the addon World Quest Group Finder or World Quest tracker ask to you if you want to find a group. 
3. Find a Group.
4. Finish the World Quest.

**Actual Behavior**
1. Go to the World Quest area. 
2. Wait for the addon World Quest Group Finder or World Quest tracker ask to you if you want to find a group. 
3. Nothing happens.
4. You aren't able to find the button manually.

**Only DiabolicUI Enabled**
I took off all the others addons and let just DiabolicUI enabled and World Quest Group Finder and World Quest tracker enabled.

**Comment by goldpaw** [comment]
Try clicking on the middle mouse button on the quest title in the tracker :)

**Comment by goldpaw** [comment]
Since there already is built-in support for one of these addons (though poorly documented so far by me, something I will remedy in the new wiki pages here) I'm closing this issue.
